services:
  web:
    build: articles
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: "postgres:15.4"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=articles
    ports:
      - "5432:5432"
  
  celery:
    build: articles
    command: celery -A articles worker --loglevel=info --concurrency=4
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=articles.settings
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
  
  celery-beat:
    build: articles
    command: celery -A core beat -l info
    environment:
      - DJANGO_SETTINGS_MODULE=articles.settings
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis