# Generated by Django 5.0.6 on 2024-06-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_article_created_at_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='avg_scores',
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name='article',
            name='number_of_scores',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
