# Generated by Django 5.0.6 on 2024-06-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_vote_vote_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='disable_unitll',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_disable',
            field=models.BooleanField(default=False),
        ),
    ]
